### PR TITLE
fix: default e2e tests 

### PR DESCRIPTION
**Pull request by Rei-x**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Currently in new nestjs app, created via `npx @nestjs/cli new` the script `npm run test:e2e` fails after changes in #2142

```
> broken@0.0.1 test:e2e
> jest --config ./test/jest-e2e.json

 FAIL  test/app.e2e-spec.ts
  AppController (e2e)
    ✕ / (GET) (44 ms)

  ● AppController (e2e) › / (GET)

    TypeError: request is not a function

      18 |
      19 |   it('/ (GET)', () => {
    > 20 |     return request(app.getHttpServer())
         |            ^
      21 |       .get('/')
      22 |       .expect(200)
      23 |       .expect('Hello World!');

      at Object.<anonymous> (app.e2e-spec.ts:20:12)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        0.403 s
Ran all test suites.
```

## What is the new behavior?

`npm run test:e2e` and `npm run lint` work

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

## Other information

There is also floating promise warning after running lint, just fyi:

image

```
/private/tmp/broken/src/main.ts
  8:1  warning  Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator  @typescript-eslint/no-floating-promises
```

### CODE REVIEW

**Review by micalevisk — APPROVED** [review]

**Comment by kamilmysliwiec** [comment]
LGTM
